In [1]:
import numpy as np
from src.dataset import ImageDataset

dataset = ImageDataset('database')

In [4]:
dataset[4].shape

(688, 1046, 3)

In [11]:
import numpy as np

tmp1 = np.random.rand(4, 3)
tmp2 = np.random.rand(6,3)
l = [tmp1, tmp2]
tmp3 = np.concatenate(l, axis=0)

In [14]:
print(np.zeros(tmp3.shape))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
